make: semaphore strictord bowls

default: 
	gcc -o Q1a_Semaphore Q1a_Semaphore.c
	gcc -o Q1a_strict_ordering Q1a_strict_ordering.c
	gcc -o Q1b_Bowls Q1b_Bowls.c
	gcc -o Q1b_Bowls_strictord Q1b_Bowls_strictord.c

1a_semaphore:
	gcc -o Q1a_Semaphore Q1a_Semaphore.c

1a_strictord:
	gcc -o Q1a_strict_ordering Q1a_strict_ordering.c

1b_bowls:
	gcc -o Q1b_Bowls Q1b_Bowls.c

1b_strictord:
	gcc -o Q1b_Bowls_strictord Q1b_Bowls_strictord.c

clean:
	rm Q1a_Semaphore
	rm Q1a_strict_ordering
	rm Q1b_Bowls
	rm Q1b_Bowls_strictord