make: semaphore strictord bowls

default: 
	gcc -o Q1a_Semaphore Q1a_Semaphore.c
	gcc -o Q1a_strict_ordering Q1a_strict_ordering.c
	gcc -o Q1b_Bowls Q1b_Bowls.c

semaphore:
	gcc -o Q1a_Semaphore Q1a_Semaphore.c

strictord:
	gcc -o Q1a_strict_ordering Q1a_strict_ordering.c

bowls:
	gcc -o Q1b_Bowls Q1b_Bowls.c

clean:
	rm Q1a_Semaphore
	rm Q1a_strict_ordering
	rm Q1b_Bowls